#!/usr/bin/perl -w

####################################################################################################
#
# Program:    crossproduct
#
# Function:   Calculates the cross product of two vectors
#
# Author:     Benjamin Bulheller
#
# Version:    $Revision: 3857 $, $Date: 2009-02-11 16:23:56 +0000 (Wed, 11 Feb 2009) $
#
# Date:       November 2007
#
####################################################################################################

use strict;                          # always use this!!!
use Data::Dumper;                    # for easy printout of arrays and hashes
use FindBin qw/$Bin/;                # sets $Bin to the directory of the script
use lib $Bin;                        # add the script's directory to the library path
use lib "$ENV{HOME}/bin/perllib/";   # adds ~/bin/perllib to the library path
use DebugPrint;                      # handy during debugging
use VectorMath;                      # for vector calculations

my ($Vector1, $Vector2);

if ($#ARGV != 5) {
	print STDERR "\nUsage:   crossproduct  x1 y1 z1  x2 y2 z2\n\n";
	exit 1;
}

$Vector1 = {x => $ARGV[0], y => $ARGV[1], z => $ARGV[2]};
$Vector2 = {x => $ARGV[3], y => $ARGV[4], z => $ARGV[5]};


print "\n\n", Dumper CrossProduct ($Vector1, $Vector2), "\n\n";


