#!/usr/bin/perl -w

####################################################################################################
#
# Program:    vectordiff
#
# Function:   Calculates the difference vector of two vectors
#
# Author:     Benjamin Bulheller
#
# Version:    $Revision: 4546 $, $Date: 2009-06-06 07:47:46 +0100 (Sat, 06 Jun 2009) $
#
# Date:       May 2009
#
####################################################################################################

use strict;                          # always use this!!!
use Data::Dumper;                    # for easy printout of arrays and hashes
use FindBin qw/$Bin/;                # sets $Bin to the directory of the script
use lib $Bin;                        # add the script's directory to the library path
use lib "$ENV{HOME}/bin/perllib/";   # adds ~/bin/perllib to the library path
use DebugPrint;                      # handy during debugging
use VectorMath;                      # for vector calculations

my ($Vector1, $Vector2, $Diff);

if ($#ARGV != 5) {
	print STDERR "\nUsage:   vectordiff  x1 y1 z1  x2 y2 z2\n\n";
	exit 1;
}

$Vector1 = {x => $ARGV[0], y => $ARGV[1], z => $ARGV[2]};
$Vector2 = {x => $ARGV[3], y => $ARGV[4], z => $ARGV[5]};

$Diff = VecDiff ($Vector1, $Vector2); 

printf "\n   x = %12.6f\n   y = %12.6f\n   z = %12.6f\n\n", $Diff->{x}, $Diff->{y}, $Diff->{z};

